"""Generate the MDX API reference for the docs site via griffe static analysis.

Renders ``site/src/content/docs/docs/reference/*.mdx`` (Astro Starlight) from
the docstrings and signatures of ``effaced`` and ``effaced_stripe``.

Constraint — pure static analysis: this script must NEVER import ``effaced``
or ``effaced_stripe``. CI runs it with only the ``docs`` dependency group
installed, so the packages may be absent; griffe reads the source trees
directly. Type annotations are rendered as text, never resolved.

Run with ``uv run python scripts/gen_api_docs.py``. Output is deterministic:
no timestamps, no absolute paths, stable ordering — running twice produces
byte-identical files.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import cast

import griffe

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "site" / "src" / "content" / "docs" / "docs" / "reference"
GENERATED_MARKER = "{/* Generated by scripts/gen_api_docs.py — do not edit. */}"

SymbolMap = dict[str, griffe.Object]
RefIndex = dict[str, str]


@dataclass(frozen=True)
class PageSpec:
    """One generated reference page.

    Attributes:
        slug: Output file stem and URL segment under ``/docs/reference/``.
        title: Sidebar / page title.
        module: Dotted path of the module whose exports the page documents.
        order: Starlight sidebar order (index page is 0).
    """

    slug: str
    title: str
    module: str
    order: int


PAGES: tuple[PageSpec, ...] = (
    PageSpec("erasure", "Erasure", "effaced.erasure", 1),
    PageSpec("export", "Export", "effaced.export", 2),
    PageSpec("consent", "Consent", "effaced.consent", 3),
    PageSpec("audit", "Audit", "effaced.audit", 4),
    PageSpec("resolvers", "Resolvers", "effaced.resolvers", 5),
    PageSpec("saga", "Saga & Outbox", "effaced.saga", 6),
    PageSpec("annotations", "Annotations", "effaced.annotations", 7),
    PageSpec("manifest", "Manifest", "effaced.manifest", 8),
    PageSpec("categories", "Categories", "effaced.categories", 9),
    PageSpec("exceptions", "Exceptions", "effaced.exceptions", 10),
    PageSpec("sqlalchemy-adapter", "SQLAlchemy adapter", "effaced.adapters.sqlalchemy", 11),
    PageSpec("effaced-stripe", "effaced-stripe", "effaced_stripe", 12),
)

_CODE_SPAN = re.compile(r"(`+[^`]+`+)")
_REF = re.compile(r":([a-z]+):`([^`]+)`")  # targets may wrap across source lines
_ENUM_BASES = frozenset({"Enum", "StrEnum", "IntEnum", "Flag", "IntFlag"})


# --- Loading & symbol selection


def _load(name: str, search_paths: list[Path]) -> griffe.Module:
    """Load a package statically with Google docstring parsing."""
    loaded = griffe.load(
        name,
        search_paths=search_paths,
        docstring_parser=griffe.Parser.google,
        resolve_aliases=True,
    )
    if not isinstance(loaded, griffe.Module):
        msg = f"{name} did not load as a module"
        raise TypeError(msg)
    return loaded


def _public_names(pkg: griffe.Module) -> tuple[str, ...]:
    """Return the package's ``__all__`` names, minus dunders like ``__version__``."""
    return tuple(str(name) for name in pkg.exports or () if not str(name).startswith("_"))


def _resolve(module: griffe.Module, name: str) -> griffe.Object | None:
    """Resolve a member through aliases; ``None`` if absent or unresolvable.

    The file-per-class layout makes some modules shadow same-named symbols
    (``storage/bind_tables.py`` holds ``bind_tables()``); when resolution
    lands on such a module, the inner symbol wins. Plain submodules
    (``annotations/subject_link.py`` on the annotations page) yield ``None``.
    """
    member = module.members.get(name)
    if member is None:
        return None
    if isinstance(member, griffe.Alias):
        try:
            member = member.final_target
        except griffe.AliasResolutionError:
            return None
    if isinstance(member, griffe.Module):
        return _resolve(member, name) if name in member.members else None
    return member


def _page_module(page: PageSpec, effaced: griffe.Module, stripe: griffe.Module) -> griffe.Module:
    """Locate the loaded module a page documents."""
    if page.module == "effaced_stripe":
        return stripe
    found = effaced[page.module.removeprefix("effaced.")]
    if not isinstance(found, griffe.Module):
        msg = f"{page.module} is not a module"
        raise TypeError(msg)
    return found


def _select_symbols(module: griffe.Module, public: tuple[str, ...]) -> SymbolMap:
    """Pick the module's members that appear in the package ``__all__``, sorted."""
    picked: SymbolMap = {}
    for name in module.members:
        if name in public:
            obj = _resolve(module, name)
            if obj is not None:
                picked[name] = obj
    return dict(sorted(picked.items(), key=lambda kv: (kv[0].lower(), kv[0])))


def _public_members(cls: griffe.Class) -> dict[str, griffe.Object]:
    """Members defined on the class body itself, minus privates and pydantic noise."""
    out: dict[str, griffe.Object] = {}
    for name, member in cls.members.items():
        if name.startswith("_") or name == "model_config" or isinstance(member, griffe.Alias):
            continue
        out[name] = member
    return dict(sorted(out.items(), key=lambda kv: (kv[0].lower(), kv[0])))


def _is_enum(cls: griffe.Class) -> bool:
    """Whether the class derives directly from an enum base."""
    return any(str(base).rsplit(".", 1)[-1] in _ENUM_BASES for base in cls.bases)


def _is_protocol(cls: griffe.Class) -> bool:
    """Whether the class is a ``typing.Protocol`` definition."""
    return any(str(base).rsplit(".", 1)[-1] == "Protocol" for base in cls.bases)


# --- Text utilities — anchors, escaping, cross-references


def _anchor(heading: str) -> str:
    """Starlight/GitHub-style slug of a heading (lowercase, punctuation stripped)."""
    cleaned = re.sub(r"[^0-9a-z\s_-]", "", heading.lower())
    return re.sub(r"\s+", "-", cleaned.strip())


def escape_mdx(text: str) -> str:
    """Escape MDX-significant characters in prose, leaving code spans intact."""
    parts = _CODE_SPAN.split(text)
    for i in range(0, len(parts), 2):
        seg = parts[i]
        for char, repl in (("{", "\\{"), ("}", "\\}"), ("<", "\\<"), (">", "\\>")):
            seg = seg.replace(char, repl)
        parts[i] = seg
    return "".join(parts)


def _ref_link(role: str, target: str, index: RefIndex) -> str:
    """Convert one Sphinx role reference to a markdown link or code span."""
    path = "".join(target.split()).lstrip("~")
    parts = path.split(".")
    if target.startswith("~"):
        display = parts[-1]
    elif role == "meth" and "." in path:
        display = ".".join(parts[-2:])
    else:
        display = path
    for key in (path, ".".join(parts[-2:]), parts[-1]):
        href = index.get(key)
        if href is not None:
            return f"[`{display}`]({href})"
    return f"`{display}`"


def convert_refs(text: str, index: RefIndex) -> str:
    """Replace every ``:role:`target``` reference in prose."""
    return _REF.sub(lambda m: _ref_link(m.group(1), m.group(2), index), text)


def _prose(text: str, index: RefIndex) -> str:
    """Render docstring prose: cross-refs converted, then MDX-escaped."""
    return escape_mdx(convert_refs(text.strip(), index))


def _inline(text: str, index: RefIndex) -> str:
    """Single-line prose for list items (newlines collapsed)."""
    return _prose(" ".join(text.split()), index)


def _first_sentence(text: str) -> str:
    """Plain-text first sentence of a docstring, for frontmatter descriptions.

    pydocstyle (D205/D400) guarantees the summary line is a single sentence,
    so the first line is taken verbatim — naive period-splitting would
    truncate "Art. 7 consent" to "Art.".
    """
    first = text.strip().splitlines()[0] if text.strip() else ""
    return first.replace("``", "").replace("`", "")


# --- Signatures


def _fmt_param(param: griffe.Parameter) -> str:
    """Format one parameter with annotation, default, and star prefixes."""
    variadic = param.kind in (griffe.ParameterKind.var_positional, griffe.ParameterKind.var_keyword)
    prefix = ""
    if param.kind is griffe.ParameterKind.var_positional:
        prefix = "*"
    elif param.kind is griffe.ParameterKind.var_keyword:
        prefix = "**"
    out = f"{prefix}{param.name}"
    if param.annotation is not None:
        out += f": {param.annotation}"
    if param.default is not None and not variadic:
        out += f" = {param.default}" if param.annotation is not None else f"={param.default}"
    return out


def _param_list(params: list[griffe.Parameter]) -> list[str]:
    """Render parameters with ``/`` and ``*`` section markers."""
    out: list[str] = []
    pos_only_open = False
    seen_star = False
    for param in params:
        if param.kind is griffe.ParameterKind.positional_only:
            pos_only_open = True
        elif pos_only_open:
            out.append("/")
            pos_only_open = False
        if param.kind is griffe.ParameterKind.keyword_only and not seen_star:
            out.append("*")
            seen_star = True
        if param.kind is griffe.ParameterKind.var_positional:
            seen_star = True
        out.append(_fmt_param(param))
    if pos_only_open:
        out.append("/")
    return out


def _format_signature(fn: griffe.Function, display_name: str) -> str:
    """Build a full ``def`` line from a function's parameters and return type."""
    params = list(fn.parameters)
    if params and params[0].name in ("self", "cls"):
        params = params[1:]
    keyword = "async def" if "async" in fn.labels else "def"
    returns = f" -> {fn.returns}" if fn.returns is not None else ""
    return f"{keyword} {display_name}({', '.join(_param_list(params))}){returns}"


def _class_fence(name: str, cls: griffe.Class) -> list[str]:
    """Signature fence: class line plus constructor params or annotated fields."""
    bases = ", ".join(str(base) for base in cls.bases)
    head = f"class {name}({bases}):" if bases else f"class {name}:"
    body: list[str] = []
    init = cls.members.get("__init__")
    if isinstance(init, griffe.Function):
        body.append(f"    {_format_signature(init, '__init__')}")
    elif not _is_enum(cls):
        for fname, member in _public_members(cls).items():
            if isinstance(member, griffe.Attribute) and member.annotation is not None:
                default = f" = {member.value}" if member.value is not None else ""
                body.append(f"    {fname}: {member.annotation}{default}")
    if not body:
        body.append("    ...")
    return ["```python", head, *body, "```"]


def _constant_line(name: str, obj: griffe.Attribute) -> str:
    """Signature line for a module-level constant."""
    annotation = f": {obj.annotation}" if obj.annotation is not None else ""
    value = f" = {obj.value}" if obj.value is not None else ""
    return f"{name}{annotation}{value}"


# --- Docstring sections → markdown


def _args_items(items: list[griffe.DocstringParameter], index: RefIndex) -> list[str]:
    """Render an Args section as a bulleted list."""
    lines = ["", "**Args:**", ""]
    for item in items:
        typed = f" (`{item.annotation}`)" if item.annotation is not None else ""
        lines.append(f"- **{item.name}**{typed}: {_inline(item.description, index)}")
    return lines


def _labeled_items(label: str, items: list[griffe.DocstringElement], index: RefIndex) -> list[str]:
    """Render Returns/Yields/Raises/Warns items as a small labeled list."""
    lines = ["", f"**{label}:**", ""]
    for item in items:
        typed = f"`{item.annotation}` — " if item.annotation is not None else ""
        lines.append(f"- {typed}{_inline(item.description, index)}")
    return lines


def _examples_block(
    items: list[tuple[griffe.DocstringSectionKind, str]], index: RefIndex
) -> list[str]:
    """Render an Examples section: prose paragraphs and python fences."""
    lines = ["", "**Examples:**"]
    for kind, content in items:
        if kind is griffe.DocstringSectionKind.examples:
            lines += ["", "```python", *content.splitlines(), "```"]
        else:
            lines += ["", _prose(content, index)]
    return lines


def _admonition_block(section: griffe.DocstringSectionAdmonition, index: RefIndex) -> list[str]:
    """Render a Note/Warning admonition as a blockquote, doctests as fences."""
    label = str(section.title or section.value.kind or "Note").strip()
    if label.lower() in ("example", "examples"):  # griffe parses "Example:" as admonition
        code = section.value.contents.splitlines()
        return ["", f"**{label}:**", "", "```python", *code, "```"]
    body = _prose(section.value.contents, index).splitlines()
    quoted = [f"> {line}".rstrip() for line in body]
    return ["", f"> **{label}:**", *quoted]


_LABELED_SECTIONS: dict[type[griffe.DocstringSection], str] = {
    griffe.DocstringSectionReturns: "Returns",
    griffe.DocstringSectionYields: "Yields",
    griffe.DocstringSectionRaises: "Raises",
    griffe.DocstringSectionWarns: "Warns",
}


def _render_section(section: griffe.DocstringSection, index: RefIndex) -> list[str]:
    """Dispatch one parsed docstring section to its markdown renderer."""
    for section_type, label in _LABELED_SECTIONS.items():
        if isinstance(section, section_type):
            items = cast("list[griffe.DocstringElement]", section.value)
            return _labeled_items(label, items, index)
    if isinstance(section, griffe.DocstringSectionText):
        return ["", _prose(section.value, index)]
    if isinstance(
        section, griffe.DocstringSectionParameters | griffe.DocstringSectionOtherParameters
    ):
        return _args_items(list(section.value), index)
    if isinstance(section, griffe.DocstringSectionExamples):
        return _examples_block(list(section.value), index)
    if isinstance(section, griffe.DocstringSectionAdmonition):
        return _admonition_block(section, index)
    return []  # attributes are rendered as the Fields list; rest unused


def _render_docstring(doc: griffe.Docstring | None, index: RefIndex) -> list[str]:
    """Render every supported section of a docstring."""
    if doc is None:
        return []
    lines: list[str] = []
    for section in doc.parsed:
        lines.extend(_render_section(section, index))
    return lines


def _attr_descriptions(doc: griffe.Docstring | None) -> dict[str, str]:
    """Attribute descriptions declared in a Google ``Attributes:`` section."""
    out: dict[str, str] = {}
    if doc is None:
        return out
    for section in doc.parsed:
        if isinstance(section, griffe.DocstringSectionAttributes):
            for item in section.value:
                out[item.name] = item.description
    return out


# --- Symbol rendering


def _render_fields(cls: griffe.Class, index: RefIndex) -> list[str]:
    """Render annotated class attributes (pydantic fields) as a Fields list."""
    descriptions = _attr_descriptions(cls.docstring)
    rows: dict[str, str] = {}
    for name, member in _public_members(cls).items():
        if isinstance(member, griffe.Attribute) and member.annotation is not None:
            doc = member.docstring.value if member.docstring else ""
            desc = descriptions.get(name, doc)
            suffix = f": {_inline(desc, index)}" if desc else ""
            rows[name] = f"- **{name}** (`{member.annotation}`){suffix}"
    for name, desc in descriptions.items():
        if name not in rows:
            rows[name] = f"- **{name}**: {_inline(desc, index)}"
    if not rows:
        return []
    return ["", "**Fields:**", "", *rows.values()]


def _render_enum_table(cls: griffe.Class, index: RefIndex) -> list[str]:
    """Render enum members as a member → value markdown table."""
    members = [
        (name, member)
        for name, member in cls.members.items()
        if not name.startswith("_") and isinstance(member, griffe.Attribute)
    ]
    documented = any(member.docstring for _, member in members)
    header = ["| Member | Value |", "| --- | --- |"]
    if documented:
        header = ["| Member | Value | Description |", "| --- | --- | --- |"]
    rows: list[str] = []
    for name, member in members:
        value = str(member.value).strip("'\"") if member.value is not None else ""
        row = f"| `{name}` | `{value}` |"
        if documented:
            doc = member.docstring.value if member.docstring else ""
            row += f" {_inline(doc, index)} |"
        rows.append(row)
    return ["", *header, *rows]


def _render_methods(cls_name: str, cls: griffe.Class, index: RefIndex) -> list[str]:
    """Render public methods with ``### Class.method`` headings."""
    lines: list[str] = []
    for name, member in _public_members(cls).items():
        if not isinstance(member, griffe.Function):
            continue
        lines += ["", f"### {cls_name}.{name}", ""]
        lines += ["```python", _format_signature(member, name), "```"]
        lines += _render_docstring(member.docstring, index)
    return lines


def _render_class(name: str, cls: griffe.Class, index: RefIndex) -> list[str]:
    """Render a class symbol: signature, docstring, fields/table, methods."""
    lines: list[str] = []
    if _is_protocol(cls):
        lines += ["*Protocol — implement these members in your own class; do not subclass.*", ""]
    lines += _class_fence(name, cls)
    lines += _render_docstring(cls.docstring, index)
    if _is_enum(cls):
        lines += _render_enum_table(cls, index)
    else:
        lines += _render_fields(cls, index)
        lines += _render_methods(name, cls, index)
    return lines


def _render_symbol(name: str, obj: griffe.Object, index: RefIndex) -> list[str]:
    """Render one exported symbol under a ``## Name`` heading."""
    lines = ["", f"## {name}", ""]
    if isinstance(obj, griffe.Class):
        return lines + _render_class(name, obj, index)
    if isinstance(obj, griffe.Function):
        fence = ["```python", _format_signature(obj, name), "```"]
        return lines + fence + _render_docstring(obj.docstring, index)
    if isinstance(obj, griffe.Attribute):
        fence = ["```python", _constant_line(name, obj), "```"]
        return lines + fence + _render_docstring(obj.docstring, index)
    return lines + _render_docstring(obj.docstring, index)


# --- Page assembly


def _frontmatter(title: str, description: str, order: int) -> list[str]:
    """Starlight frontmatter block plus the generated-file marker."""

    def quote(value: str) -> str:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

    return [
        "---",
        f"title: {quote(title)}",
        f"description: {quote(description)}",
        "sidebar:",
        f"  order: {order}",
        "---",
        "",
        GENERATED_MARKER,
    ]


def _finish(lines: list[str]) -> str:
    """Join lines, collapse blank runs, end with exactly one newline."""
    text = re.sub(r"\n{3,}", "\n\n", "\n".join(lines))
    return text.rstrip("\n") + "\n"


def _render_page(page: PageSpec, module: griffe.Module, symbols: SymbolMap, index: RefIndex) -> str:
    """Render one reference page to MDX."""
    module_doc = module.docstring.value if module.docstring else ""
    lines = _frontmatter(page.title, _first_sentence(module_doc), page.order)
    lines += _render_docstring(module.docstring, index)
    for name, obj in symbols.items():
        lines += _render_symbol(name, obj, index)
    return _finish(lines)


def _render_index_page(page_symbols: dict[str, SymbolMap]) -> str:
    """Render the reference landing page linking every page and symbol."""
    description = "Generated API reference for the effaced and effaced-stripe packages."
    lines = _frontmatter("API reference", description, 0)
    lines += ["", description]
    for page in PAGES:
        lines += ["", f"## [{page.title}]({page.slug}/)", ""]
        links = [f"[`{name}`]({page.slug}/#{_anchor(name)})" for name in page_symbols[page.slug]]
        lines.append(" · ".join(links))
    return _finish(lines)


def _build_index(page_symbols: dict[str, SymbolMap]) -> RefIndex:
    """Map symbol names, ``Class.method`` pairs, and module paths to links."""
    index: RefIndex = {}
    for page in PAGES:
        index[page.module] = f"../{page.slug}/"
        for name, obj in page_symbols[page.slug].items():
            index[name] = f"../{page.slug}/#{_anchor(name)}"
            if not isinstance(obj, griffe.Class):
                continue
            for mname, member in _public_members(obj).items():
                if isinstance(member, griffe.Function):
                    index[f"{name}.{mname}"] = f"../{page.slug}/#{_anchor(f'{name}.{mname}')}"
    return index


# --- Checks & entry point


def _unclaimed(public: tuple[str, ...], claimed: set[str], pkg: str) -> list[str]:
    """``__all__`` names no page documents — forces conscious PageSpec updates."""
    return [f"{pkg}.{name}" for name in public if name not in claimed]


def _collect(effaced: griffe.Module, stripe: griffe.Module) -> dict[str, SymbolMap]:
    """Select the documented symbols for every page, failing on unclaimed names."""
    effaced_public = _public_names(effaced)
    stripe_public = _public_names(stripe)
    page_symbols: dict[str, SymbolMap] = {}
    claimed: dict[str, set[str]] = {"effaced": set(), "effaced_stripe": set()}
    for page in PAGES:
        public = stripe_public if page.module == "effaced_stripe" else effaced_public
        symbols = _select_symbols(_page_module(page, effaced, stripe), public)
        page_symbols[page.slug] = symbols
        claimed["effaced_stripe" if page.module == "effaced_stripe" else "effaced"] |= set(symbols)
    missing = _unclaimed(effaced_public, claimed["effaced"], "effaced")
    missing += _unclaimed(stripe_public, claimed["effaced_stripe"], "effaced_stripe")
    if missing:
        for name in missing:
            print(f"error: {name} is exported but no PageSpec claims it", file=sys.stderr)
        print("Add the symbol to a page in scripts/gen_api_docs.py PAGES.", file=sys.stderr)
        raise SystemExit(1)
    return page_symbols


def _write(outputs: dict[str, str]) -> None:
    """Clear stale ``*.mdx`` files and write the new set."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in sorted(OUT_DIR.glob("*.mdx")):
        stale.unlink()
    for filename in sorted(outputs):
        (OUT_DIR / filename).write_text(outputs[filename], encoding="utf-8")


def main() -> int:
    """Generate every reference page; non-zero exit on any consistency failure."""
    effaced = _load("effaced", [ROOT / "packages" / "effaced" / "src"])
    stripe = _load(
        "effaced_stripe",
        [ROOT / "packages" / "effaced-stripe" / "src", ROOT / "packages" / "effaced" / "src"],
    )
    page_symbols = _collect(effaced, stripe)
    index = _build_index(page_symbols)
    outputs: dict[str, str] = {"index.mdx": _render_index_page(page_symbols)}
    for page in PAGES:
        module = _page_module(page, effaced, stripe)
        outputs[f"{page.slug}.mdx"] = _render_page(page, module, page_symbols[page.slug], index)
    broken = sorted(name for name, text in outputs.items() if _REF.search(text))
    if broken:
        for name in broken:
            print(f"error: unconverted :role:`...` reference survives in {name}", file=sys.stderr)
        return 1
    _write(outputs)
    print(f"wrote {len(outputs)} pages to {OUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
